package day4

import (
	"fmt"
	"testing"
)

func TestGetMatrixGraphConnections(t *testing.T) {
	result := getMatrixGraphConnections(0, 0, 1, 1)
	expected := []Connection{}
	compareConnections(t, result, expected)

	result = getMatrixGraphConnections(0, 0, 10, 10)
	expected = []Connection{
		Connection{direction: "→", coordinates: [2]uint32{0, 1}},
		Connection{direction: "↓", coordinates: [2]uint32{1, 0}},
		Connection{direction: "↘", coordinates: [2]uint32{1, 1}},
	}
	compareConnections(t, result, expected)

	result = getMatrixGraphConnections(1, 1, 3, 3)
	expected = []Connection{
		Connection{direction: "↖", coordinates: [2]uint32{0, 0}},
		Connection{direction: "↑", coordinates: [2]uint32{0, 1}},
		Connection{direction: "↗", coordinates: [2]uint32{0, 2}},
		Connection{direction: "←", coordinates: [2]uint32{1, 0}},
		Connection{direction: "→", coordinates: [2]uint32{1, 2}},
		Connection{direction: "↙", coordinates: [2]uint32{2, 0}},
		Connection{direction: "↓", coordinates: [2]uint32{2, 1}},
		Connection{direction: "↘", coordinates: [2]uint32{2, 2}},
	}
	compareConnections(t, result, expected)

	result = getMatrixGraphConnections(2, 2, 3, 3)
	expected = []Connection{
		Connection{direction: "↖", coordinates: [2]uint32{1, 1}},
		Connection{direction: "↑", coordinates: [2]uint32{1, 2}},
		Connection{direction: "←", coordinates: [2]uint32{2, 1}},
	}
	compareConnections(t, result, expected)
}

func compareConnections(t *testing.T, result []Connection, expected []Connection) {
	if len(result) != len(expected) {
		t.Errorf("Diff sizes -> expected %d but got %d", len(expected), len(result))
		t.FailNow()
	}
	for i, conn := range expected {
		if conn.direction != result[i].direction {
			t.Errorf("Wrong Cooordinates in index %d, Expected %v but got %v", i, conn.direction, result[i].direction)
			t.Errorf("\nE: %v \nR: %v", expected, result)
			t.FailNow()
		}
		if result[i].coordinates[0] != conn.coordinates[0] && result[i].coordinates[1] != conn.coordinates[1] {
			t.Errorf(`Expected 
			%v 
			but got 
			%v
			at row %d`, conn, result[i], i)
			t.FailNow()
		}
	}
}

func TestSearchMatrixConnections(t *testing.T) {
	matrix := [][]rune{
		{'.', '.', 'X', '.', '.', '.'},
		{'.', 'S', 'A', 'M', 'X', '.'},
		{'.', 'A', '.', '.', 'A', '.'},
		{'M', 'M', 'A', 'S', '.', 'S'},
		{'.', 'X', 'M', 'A', 'S', '.'},
	}
	connections := getMatrixGraphConnections(4, 1, len(matrix), len(matrix[0]))

	fmt.Println("===Test 1===")
	var expected uint32 = 0
	result := searchMatrixConnections(connections, nil, []rune{'Z'}, &matrix)
	if result != expected {
		t.Errorf(`Expected %v but got %v`, expected, result)
	}

	fmt.Println("===Test 2===")
	expected = 3
	result = searchMatrixConnections(connections, nil, []rune{'M'}, &matrix)
	if result != expected {
		t.Errorf(`Expected %v but got %v`, expected, result)
	}

	fmt.Println("===Test 3===")
	expected = 2
	result = searchMatrixConnections(connections, nil, []rune{'M', 'A', 'S'}, &matrix)
	if result != expected {
		t.Errorf(`Expected %v but got %v`, expected, result)
	}
}

func TestCountExample1(t *testing.T) {
	//given
	//MatrixGraph
	input := [][]rune{
		{'.', '.', 'X', '.', '.', '.'},
		{'.', 'S', 'A', 'M', 'X', '.'},
		{'.', 'A', '.', '.', 'A', '.'},
		{'X', 'M', 'A', 'S', '.', 'S'},
		{'.', 'X', '.', '.', '.', '.'},
	}
	const expected uint32 = 4
	//when
	result := CountXmas(&input)
	//then

	if result != expected {
		t.Errorf(`Expected
		%v
		but got
		%v`, expected, result)
	}
}

func TestCountExample2(t *testing.T) {
	//given
	//MatrixGraph
	input := [][]rune{
		{'M', 'M', 'M', 'S', 'X', 'X', 'M', 'A', 'S', 'M'},
		{'M', 'S', 'A', 'M', 'X', 'M', 'S', 'M', 'S', 'A'},
		{'A', 'M', 'X', 'S', 'X', 'M', 'A', 'A', 'M', 'M'},
		{'M', 'S', 'A', 'M', 'A', 'S', 'M', 'S', 'M', 'X'},
		{'X', 'M', 'A', 'S', 'A', 'M', 'X', 'A', 'M', 'M'},
		{'X', 'X', 'A', 'M', 'M', 'X', 'X', 'A', 'M', 'A'},
		{'S', 'M', 'S', 'M', 'S', 'A', 'S', 'X', 'S', 'S'},
		{'S', 'A', 'X', 'A', 'M', 'A', 'S', 'A', 'A', 'A'},
		{'M', 'A', 'M', 'M', 'M', 'X', 'M', 'M', 'M', 'M'},
		{'M', 'X', 'M', 'X', 'A', 'X', 'M', 'A', 'S', 'X'},
	}
	const expected uint32 = 18
	//when
	result := CountXmas(&input)
	//then

	if result != expected {
		t.Errorf(`Expected
		%v
		but got
		%v`, expected, result)
	}
}

func getQuestionMatrix() [][]rune {
	//given
	text := `MMASXSSXSAMXSMMMMSMMXXSXMASAMXSMMSAMXSSSMMMXAAXMASMSMSMXSSSSMSMSMMSMSMASMSAMXXSMMXAMXXXXMMSSSXMSSMSSXMASMMSSSMSMXMXMAXMAMXXXXSXSSMMSSMXASMXM
XXAMXAXAXXMAMAASXMXSAXXAXXMASAMXMMAMAMXAAAAASMXSMAAAAAXSMAMXAAXAAXXAAAXMXSMAXMAMXASMMSMSAAAXMAMMAAASMXMXAMAMAAAMASAMXMASMSSMMMAMAASAMXSSSMMS
MMXSAMMMMSMASXMSAAAMMMSMMXMAMASMMSSMMSSSMMSMXAASMMAMMMMXMAMMSMSSSMMSMSMSAMXXSMASMAMSAAASMMMXXAMSMMMMXAMMMMASMSMSASASXMAMAAAAMMSMSMMAMXMASAAA
XMAMAXMAAXXASAAXMMMSMAXMAXMASXMAXAXAXMAMXAXMMMMMAXMXMSASAASAAAXMAXMASAAMMSSMMMAMMAMAMMMMSMMASMMSAMXXSXSAXXMSAAAMAXAMXSMMMMSXSAMAAXMAMMMXMMMS
MMSXSMSMSSMSSMMMSSMAMASASXMAXAMSMASXMMMMMMAXMXMSXMXAMXAAAMMXSXMSXMSMSMSMAAMAAMAXMXSMMMXAASMAXMASMSMXMASXSMASMMSMXMAMASAXSXAAMASMMMMMXAMAXXAX
MAXXMAMSAXMASAAAAASXSASAMAMSXSXAAMXMXSAAASMSMAMMMSSMSMXMMMXAMAXMMASASAMMMMMSMXMMMXXXMMMSMSMSSMMMAXMASMMAMMAMAXMASMXMASAMXMMMMAMXXMASXSSMSMSS
MAMAMMMMMSMASMMMXXAXMXMAXSXXAXMASMAMMAMSXSAAXAXAAXAMAMXXSXMASMMAXXMMMAMXAMXMSAAASMMMSXMAMXAAMMXMMMMAMXMAMMASXMMASXAMMMXMXXAXMASXSSMSAASAAAAX
MXSMMMXSMXMXSXSAMXMXMASXMMAMMMSXAMMMAAMMMMMMSSSMSSSMSSXXMAAAAXXSMSMXSMMMAXAASMSMSAMAAAXXSMXMXAMXMMMAXASAXXASMMMASMSMAMAXXSSMSASAAAAMMMMSMXMS
SAAXSXAAXAAMMXMASXXASXSXAMAMAAMMMMMXSXMXAAAMAMAXMAXAAMMMSAMMSSMAASMXXMMSASMMMAMASXMMSSMAMMMXMXSAAASMSMSASMASAAMXXXXSASXSXSMXMASMXMMMXAMXSXAM
MSMASMMSSMXAAAMAMMMXMAMXAMXMMXSAMASMXAXSMMMMSSXMMSMMMXAXAXSXAAMMAMXSASAMXAMAMAMAMMSAAXMXXAMAAAXMXMMAAMMAMMMMMSXXXMAMMSAAMMSAMMMXXSXSSXSASMAM
MASMXAAMAMXSMMSMSASAMMMMMSMMSMSMSMSAMSMSASMXMXMSAMAXASXSMMSMSSMMXSAXXMXAMMXAMMASMAMMMSMASXSMSSXSXSMSMMMMSSSMXXASMMSSMMMSAXSXSAXXMMAXAAMASAAX
MAMXXMMSAMMXAXAASMSMSAMXAAXMAAMAMMMMMAAMAMMASAAMASMMMMXAXASAXXXXMMXSAMSSSSSSSMAMMXMAMAMASAAXAAMSAMAMXXXXMASMAMXAAXAAXAXMMXSASMSMMMAMSMMAMXMS
MSSSMSASASASMMSXSXXXSASMSSSSMMMAMAAAMMMMMMSAMAMMMMXAMXSXMASXMMXMXAAMAMAMAAAAXMASMMSASXSXSMMMMXAMAMAMXMMXMMMXXMMSMMSAMXSAMXSAMXSAAXXXAAMXMAMX
SXAAAAAXAXMAMMMASXSMMAMXXAXXMXSMSMSSSSMSAAMMSSMSXMAXMXXAMASAXMAMMMXSAMXMAMMMMMXSAXMXMAMMSAMAMSSSMMMXMAAXSMMMASAMXAMXSAMASAMMMXMSMSMSXMMSSMSX
XMMMMMAMMMSSMSMAMAMXMSMMMXMXAMXAAXMAXAASMSMMAXMXAMXSXXSXMASMMSMSAAAXXAXXAXAMASAMXMXSMSMASASAXAASMAAASMMMMAAMMAAMSMSASASAMXAMXXXMSMAAAMAXAAMM
XSXXXXXXSAAMMAMAMAMMXAASMSMSAXMMMSMSMMMXMMAMXMSSSMAMMMMMMMSAXMASMMSMSXXSSSXSASAMXXMMAAMMSXMXMXSMSMSXSAXASMXXMMXMAAMASAMAXXXMXMMSASXSMMXSMMMA
XMXMASMMMSSMSXSAMXMAMXMXAAAMXMMAXMAMXXMASXMMSMAAAMXXAAAMAAXXMAMMSSMMSAMXXMASXXAMXXAMMMMAXAMASXMAAXMASXMMXXAMMSSMMSMMMMMMSSMMASMSAMXMXSAMXAXX
AMAAAAASAMXAMXXXXAXSAMXMMMSMAASMMMMMMXSAMXAAMMMMMAASMSXSAXSAMXXAXSAAMAMASMMMMSMMMSSSMSMMSMMAAAMSMSMAMMSAXSSXAAXXAXXXAXMAAAASAMXMMMXSAMASMMSS
MSASMSMMAMMXMMMSSSSMMAAAMAXXMMAXXAXSAAMXSSMMSAMXMMXSAAXXAMSAMAMMMXMMXXAAAXAAMAAAXAMAAAAAAXXASXMAMAMAMSAMXAXMASMMSSXSAXMMSSMMASMMXSAXXMSMMAAA
XAAXAXXSMMSMSXAAAXAASXSSMXSXXSMMMMSMMSMXAAAASXMAXXAMMMMMMMXAMMXAAXSSMSMMMSSSSSSMSMSMMMMSXMMAMXSXSSSSMSAMXMXAMXAAAAAXMASXMAAMAMAAAMXMMMMAMMMS
AMAMAMXSXAAAAMSSXSAMXAAXMAXMXSAAXSXMAMXMMSMMSASMSSXSXAAAASMMMXSMXXAAXSASAMXAXAMMMXXXSXAMMSSMSAMXXMAXXXXAAXMSASMMMMSMMAAASMMMAXMMXSASASMAMXXA
XSAMXMAXMXSSXMAMMMXAMXMAMSXSASMMMXAMXXAXXAMAXXAXXXAXXMSSMSAMAXMASMSMMXAMASMSMXSAXMAMXMAXAAAXSAMMSMMMMMMSXSAMMXXMMMMAMASAMXSXSMXSMSAXSAMXMMSS
AMXSAMXAMXMAMMAMMMMXMASMMAAMASXXMSXMAXXMXXMXSAMMMMMMXXAXASAMXSMMMMAAAMSMXXAXMASXSMASAXMSMSSMSAMAMAAAAAAXAXXXAXXMAXSAMXMAXAXXMAXMXMXMXMMASXAA
XXAXXMSXSAMAMMASMXSASASAMMSMAMMAMMMMMMSAMXSASAAASAXSXMASMMXMASAAXXXMXMAMSMSMMXSAXMASXAXAAMXASAMASXSMXXSMXMASMMMSAXXXSAMMMXSAMASMMMMMMXSASMMA
SMXMXXXAXXXAMXAMMASXSXMAMAXMAMMAMXXSAAMSAXMASXXASMXSXMAMXSSMMXMMMMSMSAMAAAMASMMXMMXXMXMMXMMXMXMMSXMMSSMMAAAMAAAMMMXSMMXMASMAMASMAAAMSAMXSAXS
SASMSMMXMMSSSMSSMMMAMMMSMMSMSMSMSMAMMSMMMMMMMAMMMMAXAMXMMAAAAMSSMAAAMMXSMSMAXAASXXASXSXSAXSMSSMXMASXMAAAMMSSMMMSSMMXAAAMSMSXMASMSXSXMMSMMMMX
MAMAAAMASXAAXAXAXXMMMAAXAXMXXXAAAMXMAMXMAXSXMXMSAMASMMSSMSXMASAAMSMSMXMXXAMXSMMSAMXXAAAXMSAAAXXAAMXMMSMMSAMMASXXAMMSSMXSXASMMMSXXXXASASAAXAS
MAMSMXSASMMSMSMMSSMASMSSMMSAMMMSMSMMASAMSSSMASASAMXSAAAXXMAASMXSMMXXMASXSAMXMXMXMMMMMMMMXAMMMSSMMMAMAXMAMASMASASAMXMXAXSMMMAAMXAMXSAMASMMMXX
SSXMMMMMSAAMMMAXAASAXSXAAAMASMMXXAXMASMSXAXMAMXXSMMXMMMMXXSXMAAMMSAXSAMMAAMXAXMAMAAAXAASXMXMAXAAASASASASXMMMASAMMSXMMSMMAASXMSMSMXMAMAMASXSM
SXAAXXAAMMMMSMMMSMMMSASXMMMAMXASXMSMASXAMMMMSSMMASXSMMAXMXXASMXMAMXXMASMSMMMMMMAXSXSSSSSXXAMASMSAXAMASAMXSAMXSAMXSAXMAASMMMMAXAMXAXMAMXXMAXM
MSSMMSMSSMSAMXMXMMAXSAXXAMXSMMAMAMAMMSAMXXAXAAASMAXAASAXXASXMASMAXMASAAXAMMAMMMSMMAMAMAMMSMSAXXMXMXMXMMSXSASAXMMXSAMSSXMMMSMSMMMXMSAMXSMMMMS
XAMAXAXXAAMXSAMXAMAMMAMSXMAXAMXMAXAMXSMXMXSSSSMMXMMSMMASMASAMAMSMMXMMMXSASXSXSMMAMMMAMAMXAMXMXXSMMSSMAAMMMXMAXMMMMAMAXMASAASAMXSAMMAMXAAAAAS
MMMSSMSSMMMASMSSXMAAMMMSAMASXMMMAXXSMXMAMSMAAXAAAXAAXMAMMXMAMMXAMXMXAMAXMAMXXSAMMMASMSSSMMSMSXXXAAAAMMMSSMSSMMSAASXMXSAAMMXSMXAMMSSSMSSSMMSS
MAAXAMXAXSMMXXMASMXXXAAMXMASMSAMMMSAMSMMXAMMMMMSXASASMMMSSSXMXSXXSAAXMSSMSXSASAMXSMSAAMAASAASMXSMMSSMXAAAXAAAAMXMSXAAMMSSSXMXMMSXMAAAAXMMMXX
MMMSAMMXMMASXASAMSAXXMSMXMASASMSAXXAMSASMMSAXAAXXMXXXAXAAAAXSMAMXSSSSXXAAXAMMMASAMXMMSMSMMMAMMXMMAMAMMMSSMSSMSSSMXMMMSMAAMAMMMAAAMSMMMSMMSXM
SAMMXMMAMXAMSMMAMMMSAAAMSSMMAMAMMSSMMSXMAXXASMSMMMASMSMMSMMSMAAMXXAMXMSMMMMMASAMXMXAXXAMXSMXASMMSASAMAXMMAXMAAXAXXMMAMXMAMAMAMSSSMMXSMAAASAM
MMSMAASASMAXXXMXMAAXMMMSMAMMAMAMXMAMXXMSXMXMXXAAASMXAMAAAASXMMSXMMSMXMASAAAMXSSXAMXSAMAMAXMSXAAASXSAXXXMMSMMMMSAMMMSSSXXASASXXXMAMXASXXMMSAM
MAAMMMMAXXMMXMXXMMXSAXMAMAMSMSSSXMAMMAMXMMASMMSSMSAMSMMMSXSASAMAMXAMAXASMSSSXMMMXMAMXSAMXSAMXMMXSXMMSSXMAXXSAMXAMMAAXAXXXSAXXMASAMMXMASMXSXM
MSSSSSMMMSXMASASMAXSAMSMSXMXAXMAMMSXSAMAMSASAAMAMMMMAAAXXMSAMASMMSSSSMAMAXMAMMAXAMMSAMASASASXXSASMSAAXAMXMMSAMMAXMAMXAXMMMXMASMMSMSAMXMMAMXX
XXAAMAAXMMASXAAMXAMMMMMXMMMMSMXSXMAASXMAXMASMMSXMAMXXXMMAMXXMAMXAXAAMXSSMMMAAXMSXSAAAMAAASAMMMMASAMMSSMMSSMSAMXXSXSMSSSMAAASXMXAXXMXSSXMAMMM
MSMMMSMMSSMMSMSMSMMMAXXAXAAAXMAXAMMMMMMSXMXMXMXXMMSSMSSXMMMAMXMMSMMMMAXAAASAXAMSXMMSMMXSXMXMAAMAMMMAAAAAAAXSMXSXMAMAMAAMMSMXAMMSSMMSAMASAAAM
AAAAXAXAAAAAXXXAXAASMSSMSSMSAMMSMMSAMAAAMSSMMAMMMXAASAMMSAMXAAXXAMXMMMSMMMSAXSXSAMAAMXMXXXXMSASASAMMMSMMSMMXMASAMMMAMSMMMXMMAMAMAMSMSAASMSMS
SSSMSMMMSSMMSMMMMSMMAXMMAMXMMXAAAAMAMMMSXAAAMMSAAMSSMMSASMSSMMSSMSAAAMAMAXXMXMASAMXMMMSAMXMAAAMASAMSMMXMAXXSMMSAMAXAXAXXMAMXAMSMAMXAMMASAMAX
XMAAAXMAXMAAAMMAMXAMSMSSSSSSMMSSMMSMMSAXMMSMMXSASXMAAXMMSXXAASMXXSXSMMASMSSMAMAMMXSXAXMAMXMMMSMAMAMSAMMSAMXSAXMMMSXXSASASAMSAMASMSMAMMXXAMXM
SSMXAMXMSMSSXMSMMMSMMAXAAMAXSAXAAXSAAAAXSMMAAXSAMXMSSMSAMXMSMMAMXMAMMSMMMAAMAXAXXXXXAASAMXXXAXXAMXASAMAAAXASMMMSMMAAXMXMMAMSAMXSSMMSXXMSSMSA
MAASMXMXAAXXMXAAMAXAMSMMMMMMMSSMMAMMMMMXMASXMAMAXXMMXAMXMAMAMXXMAMMSAXAAMSSMMSMXMMMSXMAAMMMMMSXMXXMXXMSSMMMXAMAAAMXMXMSAMXMSMSAMXXAXXAAMXAMS
SAMAMAXSMSMASXSMMASXMXAASAAMSAXMAASAXXMASMMASXSSMMMAMXMASMSMSMASXSMMMSMMMAAAMAXAAAASAMSXXAAASXMSMXMMXAMAMXMSAMXMSMAXAMXMAMMXAMXSXMASMMSSMMMM
MAMMSAXXMAXAAAMAMAXAAXSMSMXXMASXSMSMSSSXSXSAMXMAAXMAMXSXXMAAAXXMAXAAMMMXMMMXSAMMMMMXAMAASMSXXMAAMASMMSSSMAMMXSAXAXXMMSAXMASMMMASXMXAXAAMAMXA
SAMXXMAMSAMMSSMSSSSMMMMMXMSAMMMMMAXAAAXASAMXSAMSSMSSMMMMMSMSMSMSSSSMSAAXXXAMMMSSSSMXSMMMMMAASASAMXSXAMAMMMSAAXMSXXMAMMXSXMXAAMASAASXMXMSAMXM
SSSXMASAMXSAAMAXAAAXAAXAAMSXMXAXMAMMMSMAMXMAMAMAMAAMMSXAMAAMAAAAAAAMXMMMMMASAMSAAMAAMMSXAXMAMMXSMASMSMAMMAXMASASAMSSMMSXMASXMSASAMMAMXMMAXXM
MXXXMAMAMXMMXSMMMMMSSSSMSXSAMSMSMSSXXMMXXMASXXMASXXMASMMSASMSMSMMSMXAMAXSMMMASMMMMMMSAMSAMMAXXSAMXMAXMXMXSXMAAAMMMAAAXSAMXXXAMASAXSAMAMSSSMA
XSMSMXSAMMMXXAAAXAAXMMAAMAXAMMAAAXXXAXMMMMAMAMSAMXMMASAXAAMAXXXMAXXXXSAMMAASXMAAXXAAMXMASXSMSXMAXSSSSMSMAMAMAMSMXMAMXMMAMSMMMMMXAMXAMXMAAAXS
MAAAAXSAMXAAXXMMSMMSMSMMMSSSMMSMSMXSAMXAAXXMAMMSMASMAMXMMMMXMSSMSSMMMMXXSAMMMSAMXSMSSXMXMXAAMMASAMAASAAMAXXMSXMASMASXMMAMXAAAAXSSXSSMSMMSXMA
SMSMXMXMMMAMSAXXMAXAAAXXXMAXSAMXMAXMASXXSXMMSSMASASXXSAXXXXAMXXAMAXSAMMMMXSAAXAXASAMXMMASMMAMXAMAMMMMSMXMSAMMAMAMXXMAASMSXSSSSXMMAAXAAXXMMSM
XXXXSSSMXMAASAMSXSSMSMSMMMXMMXMAMXMMXMAMAMSAAAXAMXXASAMXXAMXAAMMMXMSASAAAASMSSSMAXSAXXSAMXMAXMXSXMASXXSAAAMASXMMSXMSSMMAMAMMXXAAMMMMMMMAAAAX
MMMAMAAXXSSMMMMMAXSMXMSAAAASMSMMSASXSMSMMAMASMMXXAMXMMXAXSXMAMSAMXASAMXMMXSAXAXAMXMMSMMMMAMSXSMXXMAXMAMMSMSAXXAMXMXAXAMMMAMXXSMMMAMAAAXMMSSS
AAXAMXMMMMAXMXAMSMXMAMXSMXMMASAAAASAMAAMXSMAMAXMASMMSXSMMXAMMMSASAMMSMXMXAMXMAXSXSAAAAASMSSMASXMSMSXMXMAXXMMSSMMMSMMXSMXXASMMMAXXAXSMSSMAMAX
SMSASXAAMSAMXSXXXASXSSMXMXSMMMMMSAMAMSMSAAAAXXMXAXAMXAXXASAMXASMSXAAAMASAMSXSSSMXXMMXSMSAMAMXMAMSAMXSAMMXAXAAXAAXMXSAAMAXSXMASMMSSXXAAAMAXMX
MAMAMXSMXXMSMMMAMMXAAMAMSAMAMXXXMXSXMMSMMSSSSMMMMSAMMAMXMAXXMASASXMSMXAMMXXAMXAMAMSSXAMMASMMMSXMMMMASASASXMMSSSMSXAMMMMMSXAMXSXAXXAMMMMSSSMM
MAMSMMMSAMXAAAMAXMMMMMAMMAXXMAMXAMSASXXMAAAMAASMMSAMMSMMMSXXAAMXMMMAXMXXXXMAMSSMASAASXMSXMXAASAMXAMXSMMMSXAMXAAASMMSXXSXMXSMAMMMMMMMMMAAAAAA
MXMXAAXXMASMSXSASMAXAMXXSAMMXSAMMMMAMMAMMMSMSXMAAXAMAAASAMSSMXMMMAMAMXMASMMAXAMXMMAXMSAMXMXXXMASXXMASMSXSXSMMMMMMAXXXSMAMMMMASASASAAAMMSSMMS
SSSSSMSMMMSXMMMAMMASMSMMMXSAAMXMAMMXMXAMAAXAMXSMMMMMSSSMAAAMMSAMMSMMSSXMMASAMMSXSSSMMXMSMSMSXSAMXXMXSASAMAXMXMAMMSMXXMMXSAMXXSASMXXSXMAAXAXX
MAAAMASASAMXSMMAMXXSAAAXMAXMXMASASMMSSSSMSMSXAMASAMXXXXMMMMSAXXXXAMSAAASXMXAMXAAXAMSXAXAAAAMAMASASMMMXMAMMMMAMASMAMSASAMMAMMXMMMMMXMMMMSXSMS
MMMMMXMMMASAMXSSSSSMXSMMMMSSMXMMMXXAMAXXAMAXMXSAMASMAMMXXXAMXSMMSASMMSMSAMSSMMMMMAMXSXSMSMXMASMSAMAAAAXXMXAMXXAXXAXXAMMXSSMMMMMAMXAAMXSAAXAM
XMAXSXXXSAMMSAMAAXMXAXXXAAAXMASAMXMMMMMSMMXMAMMMSMMXSMSASAMSSXAASXMXXMXSAMAMXXSXSXMAMMAMXMASXSAMASXMSSSMSSSSSMSSMMSMMMSMAXXAAASASXMSMXMMSMAM
SSXXAXSAMXSAMAMMMMMSXMXSXMSXSAMASMSSMSASASXMAMAMXAMSMAXASMXSMMMMSAMMMXAMAMAXXAMMMAMXMAAMXSASASXSAMAAAAAXMAMAMXAXAAAAAAAMMMMMXMSMXMXAMXXXAXAM
MASAMAMASAMXSAMAXMAAMSMMMXAAMAMAXXAAXMASAMAXASAMSAMXMSMMMXMMAMMASXMASMSMSSSSSMSASMMSASXSAMMMAMAMXSMMMSMSMAMMMMMMMSSSMSXXSAMSSMMMSSSMSMSSMSSS
MAMMXMSAMMSASASXMMMXXAAXAMMSMSAMXMMMMSAMAMSMMSAXXXMASAMMMXAMAMXMMASXXAXAMXAAXAAMXAAAMMMMASAMMMSMAAAAXAXMMSSXAAXSXAXMAMASMSMAAXAAAXAAMAMMMAMA
MAMXSXMASAMXSAMASXAXMSSSXSAXAMAXAAAMMMASXMAAAXMAMSSMXAXSXMASMSSXSAMXMMMMMMMMMMMSSMMMXMXSASASXAAMASXMSSMSAXXXMMMAMASAMXMMAMMXMMMMMSMMMAMAMASM
SXSAMASAMXMASMSAMMASAAAXAMXMASXMXSXSXMAMASMSMAMSAMXMMSMSASXSAAAMMAMSMXAAAAAAASAXAAMXXSXMASAMMSMSAXXAMMAMXSMXSAXMSXMXMXXMAMMASXXXAAAASASMSASX
AAMXSAMXSXMASXMASXAMMMMMSMXSXXAMXMMMMMAMXMMMMXAAXXAMXXAMAMAMMSMMXAMAAASXSXSXSMMMXMMSMMMMMMMMMAXMMSMXSMSMMSAASXSXMMMAMSXSXMXAXAASMSMMMMMXMASA
MMMAMASXSAMXMAMAXMXSAAAXAMMXSMXMXMASAXXMAXAAMXMMSXSAMAAMSMXSAMXSSMSMSMMAMXXMMASXMSASAMAAXAXAXSMAMXMXXAXAAMMMMXMASASMSMMMASMMSMMMAAMAXSSMAMMX
XXMASAMXXAMSMSMSSMSSXSMXASMAMMXXMSMMASXSAMSMSAAAAXMASMMMXAXMASAMAMMXXASMMASASAMAAMASAMSSSMSXMASASAMAMSMMXMSAMXSASMAMAAXMAMMXAXAMMMMMSXAMXXMX
MXSXMASMSSMSAMMXAMAMXMXMSAMXSAXSAMXXSAMMSXAASMSMSSMAMMASMSSSMMMXAMXMAXMMMAMXMXSMMMXMMMAAAASAMXXMMAMAXXASAASXMXAAMMAMMMMMXSXSXSXXSAAXMXMMMSXX
XASAMXXAXAAMAMMSMMASASXXXAXXAASMMMXXMAXAMMMMMXXAAXMAMMAMAAAAASMSSMSAMXAXMMSMSXXMASMAAMMSMMSSMMXSXXMSSMAMMAMAXSMSXSMSMAMXAMAXXMAXSMXAXAXAASXM
MXSMMSSMSMMMAMXAMSMSXSXXMXMXMMMMAMXXSMMASXASAXXMASMAXMXSSMSMMXAAAAMSMSAMXAAXMSASASMSMSAXAMSAXSASAMXMAMXMXXSSMXXAXXAAMAMXAMMSAMSMMAMSSMSMMSAX
SASAAAAAMMMSSSMMMMASAMAMSASASMXSAXMAMSXXMMAMMXSMAXMAXXAMAXMMXMSMMMMAMMAMXSMXXMXMAMXMAMMMAMSMSMASMMAMXMXSMMAMSMAAMMMMXSXMXAASAMAAMAMMAMSXAMXM
MASMMXMXMAMXAAAMASMMMMAASASASXAXMXMAMSSMMXMASAMXMXMMMSASAMXXAAAXAMSMSSSMMAMAAMXMAMAMXMMSSMMXMMAMASMSXXAAXAAMAMMXMXASXMMMSMMSAMSMMSMSAMMMMSMA
MMMXAAXASAXXXSMMAMAAXSMMMMMAMMMXSAMAXMAMXSAXMASAMAAAASAMXSMSMSMSSXMMAAAMSAASAMMSSSMSAAXSASMMMMMSAMXAAMSSMXXXAMSASMASAMXAAAMSXMMAAMAMAMXAXAAM
MAMMSMSASMSXXAMMSSSMMXMASAMAMXMASASXMSAMASASXXMASASMMXSMXAXAXXXMMASMSXXMMMMMAXXAAMAMMSMSAMXAXSMMMSMMSMAAAMSXSXSASMMMAMMSSSMMMSSMMSMMSSSMSMSA
AAXMAXMAMXAMXAMXMAAAXSSMSASXSMAMSAAAMXAMXSAMXMSMXMAXSMASXXMMXSXXSXMAMMMMXAMMSMMMMMAMXMAMXMMSMSAAAMAMXXMMMASAMAMMMAXSXMMAAXXAAAMAMXXSAAAAAAXA
XXXAMMMXMMXSSXSAAMMMMAAAXAMAMAAXMMMXMSMMMMAMAAAMAMAAXSAMMMMSAMXMMMMAMMASMXSAAAXAASASAMXMXXXMASMMMSAMMASXSAMAMXMASXMSAMMSSMAMSMSAMXMMMSMMMXMA
MMMAMXMXMXXAAASMSAAXMSMMMSSMASXSSXXXXAAAAMASXSSSSMAXMMXMXAAMASMMAAMAXSAMAXMMMXMXXSASAMXAMMMMXMXSAMXSXMAAMSSMMMXXAAAMMMAXAMMAXMSASAAAAAAXXAMM
SMASMMMAMXSMMMMXMXXXAMAMAAAMAAXAMXAMSXSSMSASAAMAXSMSMMMSSMMSXMASXMMMXXSMMMXSSSSSMXMXMXMXSASMSMMMXSAMMXMXMASMAMMMAMSMSMSSSMXMXASASAXMSSXMMSSM
AXAMAMMXSAAXXSSSSSXSAMXMMSAMXSMMMMSMSAMAMMXMMSMMMXMAXAAMAMXMASAMXSXXSAXXXMAMAAAAMASMSAXXMAXAAAXAAMAMAXXMXAXMAXXXAMXMAAASXMAXXMSXMAXMXXXAAAAM
XMXSXMAAMXMMMXAAXAXSMMSXMXASAMAMXMAMMAMMSMAMAXAXMMSASMXXAMXXMSAMASAAMAMMSSSMSMSAMXSAXMXMMSMSMSMMSSXMSMSAMSSSSSMMXMXMMSMMSSMMMXSAMXMSAXSMMSSM
MAAXMAMXSAMXSMMMMMMMMASAASAMXSXMASASXMMAAMAMASXMSAMXSMMMSSMAXSAMASMXMAMAXAAAXXXASMMAMSMSAMAAMAASMAMXMAMMAXAMXAAMXXAXMAAAAMAMAASAMAXMXMMXMAAX
ASXMASAASAXXAXSAXMAAMASXMMXMXAXSMSMMXMMXSSSMASMXMASXXAAAAAXAMXMMASAASXSXMSMMMSSXMAMAMAAMASMMSSSMMASXMAMMSMSMMSAMSSXSXSMMMSAMMXSMXXMSAMXASMMM
MMMMAMMMSMMSMXXMSSSMSAMMSMASAMXSASASXSSXXAXMAXAXXXMASMMSSXXMXXMMXSMXSMSMMMAAAXXXMAMMSMSMMXAXXMAXMASAMAMXMAXXAMAXAAXMAXXAMSASMMMXSMMMXMSMSAMS
XAAMASAAXAAXXMMSMAAXMASXAMXMAXAMAMXMAAMMMMMMASXMMMXMASAXXXXMMSXSMSXXMASAAXSMSSMSMAMXMXXMMSMMSMMSMASMMMXAMXXMSSSMMSMMAMMSXSXMXAAASAMMSMSXSAMA
MSMSXSMMXMMMMAMMSMSMMMSMMSMSMMMMMMXMMMMAXXXMAXMAAMAXAASAMXMSAMXSAMMSXAXMMMMMAAAAXASASAXAAXMAMAAAMAMXAMSMMSAAXAMXXAAXAXXXASXMSMMMSAMXAAXASXMM
XMASAMXMMAMAXXMMXMMASAMXXAXAXAAAAXMASXMSSMXMXSSSSSXSXMAMSAAMMSAMXMAXMSSXSAXXSMMMSMMAXMMMXSMSMMMXSASMMXAAASMXMMMMSSSXSXSMMMAXAAAXSMMSASMMMMMM
AMAMXMAXMAMSSSMSAASAMMSMXMXXXXSXSSMMXSXMXMXMAXXAXMAMXXAMSXSSXMASMMSSMXAASMXMASXMAXMXMSASMMXXAAXXSAXAXSAMMSXXSAAXAMXAMMSASMXMMSXXMAXSAMXXAXAX
SMMMXXASMMMXAAASAMMXSXAAAMSXMXMMMAASAMXMAMAMXXMMMSSSSMSMMAXMAMAMXMASMMMMMASMMMMSAMSAMMASASASMMMXMSMAMMASXMMMMSSSSMMMXASAMSAMXMMSSSMSAMAAMSMS
AAAXXMASAMXMSMMMSXAMXMSSMMAASASMXXMMAMMSASASMMSAAXXAXMXAMXMASMMSSXSXSASASMAAXAAMMMSAXSAMXMASAAMSAMXSXSMMAASXXXMAMXAMMMMXMAMMAXAXAMAMAMXXXAAM
SSMSXSAXMMMMASAMAXMSMAXXAXSXMASAASMXAMMXAMASAAMMSSMMMASMMXMAMSXAMXMASMSASXMMMMXSAASAMXAMXMXMMMMMAMAMASAMSMAXMSMSMSMSAMAMXMMSXSSMAMSSSMXMMMSM
XAASAAAXSAMSASXSMMAAMMMXMMMXMMMXMAASMSMMSMSMMMSAXAMXAXAXAAAAXXMASAMXMXMXMXXXXMAXMXSXMSXMXASMMSXXAMAMMSMMMMMMMAXAAXMAMMASMXMMAXASXMASXAXSXAAM
SMMMMMMXMAMMAMMSXMSXSASXSAMAMXMXXMMXMAXAAXMASAMMSMMXMMSXMMSSSMSASMSXSSMSSXXAXMXSMAMAMXAMMXAAAXMMXSAMAMXAXAAMSMSMXMXMSSXSXAXMMMMXXMXSMAMSAXSS
MXMAAXXASXMMAMASXMAASASXMASMMAXMMXSAXMMSSXSAMXMMAMMXMSMSMAXAAAMASXSAMXAAASXMXMXAMMXAMSMMAMXMMSMSMMAXSMMXSMMXAAAMASAMXMMMXMSMAAXMMXXXAMXSAMAX
AAXSXMXMMMXSXMAXAMMXMAMXSXMXSXSASASMSXXAAMMMMMMSAMSAXAAAMXMMMMMXMASMSMMMSMXSAXXXMXSSXXMAMMAXXAMAAMSMXAXMXMXSXXASMSASMMAAXMAMSMXAAMMMSXAXXMXM
SSMXAMSSSXAMXMASMMSAMXMXMAMXSAAXMASAAXAMAMAAMXAMAXXMXMSMMAXXMSXXMASMSAMSMXAMAXSAMXMXASAMAXMSMMSMSMMASAMMASMMSMAMXSAMASMSXSAMXAXSSMAAMMMMXXMX
MMAMXMAAXMXXMXAAAASASXMSSSMMMMMMMXMAMXSMMMSSSMXSMSSSMAMASMSMASXMMASMMAMAMMMMAAXAMSMAXMAMXASAMXAAXXMAMMSMASAAAMAMXMMMXAXXAMMMMSMAAXSSXAMSSMSM
MMAMAMMSMSSMMMSSMMMMMXAAAAXMAXAXMXMXMAXAXAXAMXAAMXAXMAMMXAAMAMAMMASMSMMAXAXMXSMXMAAXSSXMMXSASXMSSXMXXAXMMSXSXSASXMXSASAMXMXSAXASMMMMXSAMMAAX
MXAXMSAMAAXSAAMAMAXSAMMMSMMSMMSSMAMAMSSXMMSAMMMSAMMMXXSAMMMMMMAMAMSMAASMSMSMAXXASMXMXMASAMMAMXMAMMSXMSMSAMAXAXASMSAMAMXMAMXMXSXXXXMAAMAMMSMM
SMXXXMAMMMSAMXSAMMXMAXXAAAMXMAMMMXXXXAXMAMMMSAMAXAXSMMXMASAAXSSMSSSXMXMAAAAMAMSXSAAMSAMXSAMXMXMMSMMXXXAMXMMMSSMSAMAMXSASAXXXASMMSXSMXSXMAMAS
MASMSSSMAMSMSXMXSXMSSMMSSSMXMXSAASMSMAMSAMAAMASAMSMMASAMXMXXXSAAMAXMSMMXMXMMSMMASMXMAAXMASAMSASAAASXAMAMMMXAXXAMXSXMAMMSMSSMMXAAAMMXXMAMASAA
MAMAAAMMSMMXMASAMAXAAAAMMMMMMSMMMSAAMSMSASMXSAMMXXASMMAMSSSXXMMMMAMMAMXMSASAAAMXMMSSSSSMAXMASASXXSMXMSASAXMXXMXMASAMMSAXAAXASMSMMAMSMSAMAMAS
MXSMMMMAXMASXAMASXMSMMMSXMSASAXSMMMMMAASAMAAXXXMSSXSXMAMXAAXXXXXMSMSASMAXAMSSMXXMAXAXAAAAAXXMMMMMAMAXSAMXSAMSMMMMSAMSMMXMAMXMAXXXSXMASASXSAX
AASASMMXSMMMMMSXMMMMXSAMMASXSXXMASAXXMMMAMSMXMMXMXASMSSMMXMMMMSMAMMSASXSMMMMMMMAMXMMMXMMASMMMSAXMAXMMMSMXMMXAAAAXSXMSASXMMSSMSMSMXASMSMMAMAS
MMSAMXSASXMMMMAMXAAMXMAXMASMMMAMAMXSMSASMMAMXXMAMMMMAAXMSSSXXAXAMMASAMAXAAMAAXSXMAMXSAAXAAXAAMXSSSSXSAXMMMSSSSMXASXMSAMXAAAMXMAXASMMASAMXMAM
XAMAMSMAMSMASAAMSMXSASXMMMSAAAMMSSMMAXASAMAMXMMASAMMMMSXAASAMMMMMMASAMXSMMXMSMMSXXSAMSAMXMMXMMXMAAAAMMMMAXXAMXXSAMXXMAXSMMMSAMXMXMXMXMASAMXS
AMSSXXMAMAMASMMMSXMSASMMAMSXMMSAMAAMAMSMXMASAMSASMMAAXXMMSMMAMXAMSMMXMMMMSXMXAAAXMMXXAXAMXSMMSAMMMMMMAASXSMMMAAMMMMXSAMAAAAXMSSSSXMXSXMSXSAM
XMAMAMXASXMASASAXAAMAMAXSXXASAMAMSMMXXXAMMAMAMMXMASXSMSASAMSASMSMAAXSMMAAXAXSMMMSXAXSMMSXAXAASMMMMAMXXMMSAXAMSSMXAMXSXASMMXSAMAAAMSAMXXSMMAS
XAASMSSMSXSXSXMASMMSMMSSMSSMMASAMMASMAMAMSSMSMSXMXMAAAAMAXXMAMAASMMMMASXSSSMMXSAMASMAXAAMMMMMSAAMXSMMMSMSXMMMXAASXSMXAXXXAAMAMMMMMMASAMXASAM
XMMMXMAAMASAMAMAMXAXAAMAAAXXSAMAXSAMMAMAXAMXXASMMMMMMMMSMASMMMSMSXAAMXMSAAMAAAMAMAMSXMMXAAAMXMMMSAMAAASMMASXAXMMMXAXMMMMMSSSSMSSSXSAMMAXMMAS
SXSAASMMMAMAMXMSSMXMMSSMMMSMSAMAMMXMSXSXMSMXMXMAAMAXXAAAXASAMAAASXSMSSMMSMSSMMSMMAAXXMSMSSXSASAMMMSSMMMAXASAMSSXMSMMAAMXXXAAAAAAXMMASMSMXSAM
MASMMSXMMXSMMSAMXAXXXAAAXXAAXSMSXMAMXMAXMMMAXAMMMSSSSMSMMMSAMSSXSAMAAAAAXXAXXXAXXMMXMSAAXAASXMAMXMXMMXSAMXSMAAMAAAMAXSASXMMMMMMMMXSXMAXMAMMX
MAMAXXAXMAMAXSXSSSXAMSXMMMMSMAXAAXXSAXAXMASMSMSSMAXXXXAAAASMMMMAMAMMMMMMSMSASMSSXAAAMSMMMMMMXSAMAXMAAAMASXMXMAMAMMSSSXMAAMAXAAXMSAMXMAMMSSSM
MMSMMSSMMSSXMMAMAMAXMXMMXMAMXMMSSMASMSMMSASXAXAAMSSMSSSXMMXXAAMAMAMAMXAMAMMASMAAXSMMMXMAAMAMAMAMXSSMMMSXMAXMXMXSXXAMXAXMMMASMSSXSASAMXSXAAXM
AAAXAAAAXAMAAMSMAMXSMXMMAMXSAMMAAXAMXAMXMAMMAMMSXXAXMAMMSSMSSSSXSMSASMXSASAAXMXSXMAMXMSSXSAMASXMXXAAAAXASXMAXXAXMAMXSAMXSMMSAAMASMMMSMSAMSMS
MASMXXSMMMSXMXXMXMMAMAMSMMMSAMMSMMSSSMSSSSMASXXMMXMMMMMAAAXMAXXMAMSMXMASMSMSSXMXASAMXAAXXSXXMAAXXSSMMMSAMASXSMASASXXMSXAAAXMMMMAXAAXAMXSXMAM
MAMAMMXXMXAMMXSXSASAMAMAASMSXMAMASAMAAAMAMMXXXAMAASASXMMSSMMSSMXMASAXSXMAXAAMMAMXMAMXMMSXSAMXSSMAMXMAXMXMXMAXMXMAMASMMMMXMMXXXMAXMMSXSAXMMAM
MAXMXAMMSMSXMAXAXXSMMMSSSMAMMMSSMMASMMMMAMAAMSSMSXSASXMXAAXAAAMASMMAMSAMXMMMXASXSMSMSMAMAMXMAAAMXMAMXSAMXMMXMXSMSMAMAAAAXSMXSMMXSAAAAMMSXSXS
SSSSMMSAXAAMMSMMMMXMAXAXMMXMXMAAASAMXMASMSMAXMAAXAMMMASMSSMMSMMXMAAAMSAMAXAXXXMAXAAAAAAMAMXMMSXMASAXAMXMXMMMSAMAXMXSXSXSAAXAXAAAMMMMSMMMAMMM
XMAAAXXMMMMSAXAAAXSSXXAMMASMMXSXMXAMXSMMMAXMSMMMMMMASAMXAAXXXXSSSMXMMXASXSMSSMMAMSMSMSMSSXSAAAASXSMSMSAXAMXAMAMSMXMMAXAMXAMXSMMSSSMMAAAMAMAA
XMAMSSMMMXXMAXSSSMMASMASMASAAAXSXXASMSXXXAMMAMXSAASAMASMSMMXMAMAASXSXSXMAXMAMAMMMXAMAMAXAASMMSXMAXAAXSXSMSMXSAMASMMMSMXMSMSMSXMAAMSXSXMSMMMS
SXSXAAAXAXMMMXMAMAMAMXAMMXSMMMSAMSAMXMAXSAMXAMAMXMSASAMMMAMXMAMSMMSMAMXMASMASXMXSMMMAMAMMMMMAMAMXMMMXXMAXXMAMASXXXAAAMAMXAAAXMMMSMMMMXMAXAXX
AMXXSSMMMAMASMMAMXMASMXSSMMXSXMXMMAXAMAMSAMSAMASXMSXMASMXXXXMMMMAMAMAMMMMXMASAMAAAASXMAXXAXMAXMASAMXSAMXXXMASXMMSSMMSAMXMSMXMSXAAXAAMASASXSM
AMSMMAMAMASMXAMAMXMAMAMAXAMAMSAMXMXSSMAMMSMXAXAMMASXMXMAMSMMMSAMASXSXXAAAXMXMAMSMMMMMMMXSASMSXSMAMAMXMMMSSMASAAAMXSAMMSAMXSASXASXMMSMAMMMAAX
SXMASAMAXMXAMSMSMSMSMSAMSSMAMSSSMSMAAMMSAMXSSMSMSAMXXSMMMAAAXSASASXXMSSSSSMMMSMMASAMAMMAMAMAAAMXXXSASXMAMMAASMMMSAMXMAMASAMXMAXMAXSAMASXMSMM
MASMMMSSSMMSMMAMAAAXAMSXAASMXMASAAMSMMAMAMXAMAMAMXMSAMAAXMSMMMAMMXMMXAXXAAASAAAXMSAMASMASMMSMSMASMMAMAMSSMMMSXSAMASXMAMSMMMAMMMMXMSAMMXMAXAA
MAMAAMAMAMAMAMAMXMMMAMMMMMSMAMAMSMXMAMMSSMMXMAMMSMMXASMMMAAMMSASMMSAMMSXSSMMMSMMXSAMASMXMMAXMAMAXAXXMAMMAMAMXXMASAMXMAMMAMMAMAAXMASAMSXSASMS
MSXSMMXXAXASXMXSXXAMXAMXMAMXAMXXAXAXAMMXMASAMAMSAMXSMMASAMXSAAAAXASXSXSMAMXAAAAMXMASMXMAMMMMXAMMSMMSMXXSAMXMSMSAXAXMAMSMAMSMSXSXXXXXSAAMXSAX
AMAMXMSSMSXXMXAXAMXSSMMSMASMMSSSSSMSASAASXMASAMSASXMAXAMAMAMXSSMMXSASAMXMMSMSXSMMAMXASMMMAXSMSSXAASMASAMMMASAMSMXSASMSMXXMAXMAMMMMMMMMSMSMMM
XMAMAMAAMMXMSMMSSMXAAMAMXASAXSAAXAASAMMASAMMMMXSAMXXXMSSSMASAMAXSSMAMXMASAXAAAXASMXMXMASXMSMAMXMSXMASMASAMXXAMXAXAAAXAMSSMMSMAXMMAAAXAAXAAAS
XMASAMMMMAAMAAXAAMMSXMAXMMSAMMMMMSMMAMMMSAMASMAMAMSSSMAAASXMMMAMXMMMMASXSSMAMMMAASAXXSAMXSAMSMSAMXXXXSAMMASMSMMXMMMMSMSAAXAXXSMASMASXXSXSAAS
MXXXMSMSMSSSSSMMSMAMXSAXMXXMAAAXAAXSXMAMMAMASMXSAMAAAMMSMMXSMSMSXMAMSMAAXXMASXMXMSXSXMAMXSXMAMMMMMMMMMMSXAMAMAAMAMAAMMMMSMXSAXXAMXSAXXAAXMAS
SSXSAAASAMAAMXAAMMSSXMASMAAMSSSMSSXMSMAMSAMXSMMMAMMSMMXAMAMXAAAMMXAMAMMMSMSASMAAMSAMMMSAMXMSXXAAAAAXAAAMMSSMMMSASMMXSAMXMAMAMMMSAMXAAMMMXSAM
AAAMMMSMAMMXMMMMSAXMASAAMXMAAAAXAMXAASAMSAMXMXASAMAAASXSMSASMMSMASXSASAAAXMASMSAMXAMAAMAMXMASMSSSSSSMMXSAMSXAXMMMAAASXSAAAXAMXXMASMSMXMSAMXS
MMMMXMAXAMXXMASMMXMXMAMSAMXXMSMMMAMSMSSMSXMSMSXSXSSSSMAXXAMXMXXXMAMMXSMSSSMMMAMXSSXMMSSSMSMASXXXXMAAXAAMXMXMASXXSMMMSXSASASXSXAMSAAAXSXMASMA`

	//MatrixGraph
	input := BuildMatrixGraph(text)
	return input
}
func TestQuestionPartOne(t *testing.T) {
	input := getQuestionMatrix()
	const expected uint32 = 2336
	//when
	result := CountXmas(&input)
	//then

	if result != expected {
		t.Errorf(`Expected
		%v
		but got
		%v`, expected, result)
	}
}

func TestExamplePartTwo1(t *testing.T) {
	input := [][]rune{
		{'M', '.', 'S'},
		{'.', 'A', '.'},
		{'M', '.', 'S'},
	}
	const expected uint32 = 2
	result := CountX_mas(&input)
	if result != expected {
		t.Errorf(`Expected
		%v
		but got
		%v`, expected, result)
	}
}

func TestExamplePartTwo2(t *testing.T) {
	text := `.M.S......
..A..MSMS.
.M.S.MAA..
..A.ASMSM.
.M.S.M....
..........
S.S.S.S.S.
.A.A.A.A..
M.M.M.M.M.
..........`
	input := BuildMatrixGraph(text)
	const expected uint32 = 9
	result := CountX_mas(&input)
	if result != expected {
		t.Errorf(`Expected
		%v
		but got
		%v`, expected, result)
	}
}

func TestQuestionPartTwo(t *testing.T) {
	input := getQuestionMatrix()
	const expected uint32 = 1831
	//when
	result := CountX_mas(&input)
	//then

	if result != expected {
		t.Errorf(`Expected
		%v
		but got
		%v`, expected, result)
	}
}
